// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/generate-thumbnail.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var generate_thumbnail_default = defineTool({
  name: "generate_thumbnail",
  title: "Generate AI Thumbnail",
  description: "Generate a high-CTR YouTube/social thumbnail image from a text prompt in any language. Returns a data URL of the generated image.",
  inputSchema: {
    prompt: z.string().min(1).max(2e3).describe("Topic or description of the thumbnail (any language)."),
    size: z.enum(["16:9", "1:1", "9:16", "4:3", "21:9"]).optional().describe("Aspect ratio. Defaults to 16:9."),
    titleText: z.string().max(120).optional().describe("Optional exact headline text to render on the thumbnail.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ prompt, size, titleText }) => {
    const base = Deno.env.get("SUPABASE_URL");
    const anon = Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY");
    if (!base || !anon) {
      return { content: [{ type: "text", text: "Server not configured (missing SUPABASE_URL/anon key)." }], isError: true };
    }
    const res = await fetch(`${base}/functions/v1/ai-thumbnail-generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${anon}`, apikey: anon },
      body: JSON.stringify({ prompt, size: size ?? "16:9", titleText })
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok || !data?.imageUrl) {
      return {
        content: [{ type: "text", text: data?.error || `Thumbnail generation failed (${res.status}).` }],
        isError: true
      };
    }
    return {
      content: [
        { type: "text", text: data.fallback ? "Fallback thumbnail returned (AI provider unavailable)." : "Thumbnail generated." },
        { type: "image", data: data.imageUrl.split(",")[1] ?? "", mimeType: "image/png" }
      ],
      structuredContent: { imageUrl: data.imageUrl, fallback: !!data.fallback }
    };
  }
});

// src/lib/mcp/tools/extract-youtube-tags.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var extract_youtube_tags_default = defineTool2({
  name: "extract_youtube_tags",
  title: "Extract YouTube Tags",
  description: "Extract SEO tags and keywords from a YouTube video URL.",
  inputSchema: {
    url: z2.string().url().describe("Full YouTube video URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    const base = Deno.env.get("SUPABASE_URL");
    const anon = Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY");
    if (!base || !anon) {
      return { content: [{ type: "text", text: "Server not configured." }], isError: true };
    }
    const res = await fetch(`${base}/functions/v1/youtube-tags`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${anon}`, apikey: anon },
      body: JSON.stringify({ url })
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      return { content: [{ type: "text", text: data?.error || `Failed (${res.status}).` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/check-monetization.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var check_monetization_default = defineTool3({
  name: "check_youtube_monetization",
  title: "Check YouTube Monetization",
  description: "Check whether a YouTube channel meets monetization criteria (subs, watch hours, eligibility).",
  inputSchema: {
    channelUrl: z3.string().min(3).describe("YouTube channel URL, @handle, or channel ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ channelUrl }) => {
    const base = Deno.env.get("SUPABASE_URL");
    const anon = Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY");
    if (!base || !anon) {
      return { content: [{ type: "text", text: "Server not configured." }], isError: true };
    }
    const res = await fetch(`${base}/functions/v1/youtube-monetization`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${anon}`, apikey: anon },
      body: JSON.stringify({ channelUrl })
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      return { content: [{ type: "text", text: data?.error || `Failed (${res.status}).` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/youtube-video-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var youtube_video_info_default = defineTool4({
  name: "get_youtube_video_info",
  title: "Get YouTube Video Info",
  description: "Fetch public metadata (title, channel, thumbnails, description) for a YouTube video URL.",
  inputSchema: {
    url: z4.string().url().describe("Full YouTube video URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    const base = Deno.env.get("SUPABASE_URL");
    const anon = Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY");
    if (!base || !anon) {
      return { content: [{ type: "text", text: "Server not configured." }], isError: true };
    }
    const res = await fetch(`${base}/functions/v1/youtube-video`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${anon}`, apikey: anon },
      body: JSON.stringify({ url })
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      return { content: [{ type: "text", text: data?.error || `Failed (${res.status}).` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ultra-media-ai-hub",
  title: "Ultra Media AI Hub",
  version: "0.1.0",
  instructions: "Tools from Ultra Media AI Hub. Use `generate_thumbnail` to create viral YouTube/social thumbnails from any-language prompts. Use `get_youtube_video_info`, `extract_youtube_tags`, and `check_youtube_monetization` for public YouTube metadata and creator research. All tools operate on public data; no authentication required.",
  tools: [generate_thumbnail_default, extract_youtube_tags_default, check_monetization_default, youtube_video_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
